/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.17.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server"
import type * as bookings from "../bookings"
import type * as leads from "../leads"
import type * as reviews from "../reviews"
import type * as emailLogs from "../emailLogs"

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  bookings: typeof bookings
  leads: typeof leads
  reviews: typeof reviews
  emailLogs: typeof emailLogs
}>

export declare const api: typeof fullApi
export declare const internal: typeof fullApi
