/* eslint-disable */
/**
 * Generated Convex API types and references.
 *
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`
 * Manual edits will be overwritten when regenerated.
 */

import type { FilterApi, FunctionReference } from "convex/server"

// Type definitions for Convex functions
type EmptyObject = Record<string, never>

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * \`\`\`js
 * const myFunctionReference = api.myModule.myFunction;
 * \`\`\`
 */
const createApiProxy = (path: string[] = []): any => {
  return new Proxy(
    {},
    {
      get: (_target, prop: string) => {
        if (prop === "toString" || prop === Symbol.toStringTag) {
          return () => `api.${path.join(".")}`
        }
        const newPath = [...path, prop]
        // Return a function reference object for Convex
        const ref = {
          _type: "functionReference",
          _path: newPath.join("."),
          toString: () => newPath.join("."),
        }
        // Also make it callable as a proxy for nested access
        return new Proxy(ref, {
          get: (target, nestedProp: string) => {
            if (nestedProp === "_type" || nestedProp === "_path" || nestedProp === "toString") {
              return target[nestedProp as keyof typeof target]
            }
            return createApiProxy(newPath)[nestedProp]
          },
        })
      },
    },
  )
}

const apiProxy: FilterApi<
  {
    bookings: {
      createBooking: FunctionReference<
        "mutation",
        "public",
        {
          customerName: string
          customerEmail: string
          customerPhone: string
          vehicleType: string
          vehicleMake?: string
          vehicleYear?: string
          serviceSlug: string
          neighborhood: string
          scheduledDate: string
          scheduledTime: string
          specialRequests?: string
          source: string
        },
        string
      >
      updateBookingStatus: FunctionReference<
        "mutation",
        "public",
        { bookingId: string; status: string; calendarEventId?: string },
        null
      >
      getBookings: FunctionReference<
        "query",
        "public",
        { status?: string },
        Array<{
          _id: string
          customerName: string
          customerEmail: string
          customerPhone: string
          vehicleType: string
          serviceSlug: string
          scheduledDate: string
          scheduledTime: string
          status: string
        }>
      >
    }
    leads: {
      createLead: FunctionReference<
        "mutation",
        "public",
        {
          customerName: string
          customerEmail: string
          customerPhone: string
          serviceSlug?: string
          message?: string
          source: string
        },
        string
      >
      updateLeadStatus: FunctionReference<"mutation", "public", { leadId: string; status: string }, null>
      getLeads: FunctionReference<
        "query",
        "public",
        { status?: string },
        Array<{
          _id: string
          customerName: string
          customerEmail: string
          customerPhone: string
          serviceSlug?: string
          status: string
        }>
      >
    }
    reviews: {
      createReview: FunctionReference<
        "mutation",
        "public",
        {
          customerName: string
          rating: number
          comment: string
          serviceSlug?: string
          location?: string
        },
        string
      >
      getReviews: FunctionReference<
        "query",
        "public",
        { isApproved?: boolean },
        Array<{
          _id: string
          customerName: string
          rating: number
          comment: string
          serviceSlug?: string
          location?: string
          isApproved: boolean
        }>
      >
      approveReview: FunctionReference<"mutation", "public", { reviewId: string }, null>
    }
    emailLogs: {
      createEmailLog: FunctionReference<
        "mutation",
        "public",
        {
          recipientEmail: string
          emailType: string
          subject: string
          relatedBookingId?: string
          relatedLeadId?: string
        },
        string
      >
    }
  },
  "public"
> = createApiProxy()

const internalProxy: FilterApi<EmptyObject, "internal"> = {} as FilterApi<EmptyObject, "internal">

export const api = apiProxy
export const internal = internalProxy
