/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.17.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server"
import type { DataModelFromSchemaDefinition } from "convex/server"
import type schema from "../schema"

/**
 * Define a query in this Convex app's public API.
 */
export const query = queryGeneric as typeof queryGeneric

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = mutationGeneric as typeof mutationGeneric

/**
 * Define an action in this Convex app's public API.
 */
export const action = actionGeneric as typeof actionGeneric

/**
 * Define an HTTP action.
 */
export const httpAction = httpActionGeneric

/**
 * Define an internal query.
 */
export const internalQuery = internalQueryGeneric

/**
 * Define an internal mutation.
 */
export const internalMutation = internalMutationGeneric

/**
 * Define an internal action.
 */
export const internalAction = internalActionGeneric

export type DataModel = DataModelFromSchemaDefinition<typeof schema>
